### ISSUE TITLE
[bisected] Kernel 3.9 -  asus-wmi: update wlan LED through rfkill led trigger causes disfunction

### ISSUE THREAD

**Issue by mrueg** [iksaif/acpi4asus-dkms#3]
Hello, 

I ran git bisect and this commit seems to break stuff in kernel 3.9 with my Asus Zenbook UX32VD:
https://github.com/iksaif/acpi4asus-dkms/commit/f110ad8060cbd98a3a70ad6662c502373bd68b3b

dmesg output:
asus_wmi: ASUS WMI generic driver loaded
asus_wmi: Initialization: 0x1asus_wmi: BIOS WMI version: 7.9
asus_wmi: SFUN value: 0x4a2877
input: Asus WMI hotkeys as /devices/platform/asus-nb-wmi/input/input5
asus-nb-wmi: probe of asus-nb-wmi failed with error -5

If I revert this commit, asus-nb-wmi works fine again.

see also: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1173107

**Comment by jirka-grunt** [comment]
Hello,
I can confirm the same problem (UX32VD and 3.9.4 kernel). I'm able to load module manually after boot is ended. It's loaded automatically when mentioned commit is reverted.

asus_wmi: ASUS WMI generic driver loaded
asus_wmi: Initialization: 0x1
asus_wmi: BIOS WMI version: 7.9
asus_wmi: SFUN value: 0x4a2877
input: Asus WMI hotkeys as /devices/platform/asus-nb-wmi/input/input11
asus-nb-wmi: probe of asus-nb-wmi failed with error -5
